### ISSUE TITLE
Please add an RSS feed

### ISSUE THREAD

**Issue by TheBestPessimist** [sangheon/sangheon.github.io#1]
This will make it easier to track your blog.

**Comment by sangheon** [comment]
Good idea! Added RSS feed.

**Comment by TheBestPessimist** [comment]
I can see the feed at https://sangheon.github.io/feed.xml, however it would be nice to have a button for that RSS feed, kinda like this:

![image](https://user-images.githubusercontent.com/4482210/99353092-83768280-28ac-11eb-8d87-605a45df8a49.png)

**Comment by sangheon** [comment]
Many thanks for the suggestion with snapshot! Really appreciated and done as you suggested. Actually I had same idea (adding menu for RSS) but I thought adding a RSS icon would be better. As I don't want spend more time to find a way for it, I ended up going without menu. Your comment just changed my mind. :)
